spring.application.name=Eureka-Server

# server port
server.port=9090

# Eureka Config
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false


# Log Level
logging.level.com.netflix.eureka=off
logging.level.com.netflix.discovery=off
