server.port=9097
spring.application.name=ai-service

spring.datasource.url=jdbc:mysql://localhost:3306/ai_db
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=fooddelivery_secret_key_min_32_chars_long

# Gemini API Key — Google AI Studio se lo
gemini.api.key=AIzaSyDCCGQ3VqJxlRAFXh4IRWdqLJ6xslUrRn8
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-pro:generateContent

eureka.client.service-url.defaultZone=http://localhost:9090/eureka/
eureka.instance.prefer-ip-address=true